title: ERP Implementation Projects
description: All ERP implementation projects that I had done at Medbio
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
repository: thanhxtruong/erp-implementation
collections:
- sections
